[package]
name = "reqwest_multi_thread"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
reqwest = { version = "0.12.12", features = [ "stream" ] }
tokio = { version = "1", features = [ "rt-multi-thread", "macros" ] }
